"""
Calculate the Pearson correlation coefficient (PCC) between the desired
focal spot and the focal spots generated by the random, continuous and
distributed phase plates.

The comparison is performed on a common physical focal-plane grid. Each
generated focal spot is resampled to the desired focal spot grid if its
array shape differs.

Outputs
-------
1. PCC values printed in the terminal.
2. A ranked comparison printed from highest to lowest PCC.
3. Optional CSV file: focal_spot_pcc_results.csv
"""

from __future__ import annotations

import csv
from pathlib import Path

import numpy as np


# =============================================================================
# USER CONTROLS
# =============================================================================

DESIRED_FOCAL_SPOT_FILE = Path(
    r"C:\Users\benny\OneDrive\DOCUME~1\Desktop\python\PHYSIC~1"
    r"\PHASEP~1\PHASE_~2\COMPLE~1\CHAPTE~1\GENERA~1"
    r"\PHSEPL~1\OUTPUT~1\IDEAL_~1.NPY"
)

RPP_FOCAL_SPOT_FILE = Path(
    r"C:\Users\benny\OneDrive\Documents\Desktop\python\Physics toolbox\Phase plate generator\Phaaze (Modularised_Phase_Plate_Generator)\Validation\Omega_400um\Results\RPP\omega_400um_2026-08-03_11-11-29\Arrays\Hex_grid_multilevel_focal_spot.npy"
)

CONTINUOUS_FOCAL_SPOT_FILE = Path(
    r"C:\Users\benny\OneDrive\DOCUME~1\Desktop\python\PHYSIC~1"
    r"\PHASEP~1\PHASE_~2\COMPLE~1\CHAPTE~1\GENERA~1"
    r"\PHSEPL~1\CONTIN~1\OUTPUT~1\FO4C3A~1.NPY"
)

DISTRIBUTED_FOCAL_SPOT_FILE = Path(
    r"C:\Users\benny\OneDrive\DOCUME~1\Desktop\python\PHYSIC~1"
    r"\PHASEP~1\PHASE_~2\COMPLE~1\CHAPTE~1\GENERA~1"
    r"\PHSEPL~1\CONTIN~1\OUTPUT~2\FO4C3A~1.NPY"
)

COMMON_FOCAL_SPOT_EXTENT_FILE = Path(
    r"C:\Users\benny\OneDrive\DOCUME~1\Desktop\python\PHYSIC~1"
    r"\PHASEP~1\PHASE_~2\COMPLE~1\CHAPTE~1\GENERA~1"
    r"\PHSEPL~1\OUTPUT~2\FO2C79~1.NPY"
)

# Set to None to compare the complete saved focal plane.
# For example, 400.0 compares -400 to +400 micrometres in x and y.
FOCAL_HALF_WIDTH_UM: float | None = None

# PCC is unchanged by multiplication by a positive constant, but peak
# normalisation keeps the arrays consistent with the phase-plate generator.
PEAK_NORMALISE = True

# Set to a value such as 1e-3 to compare only pixels where the desired focal
# spot is at least that fraction of its peak. Leave as None for all pixels.
REFERENCE_THRESHOLD: float | None = None

SAVE_RESULTS_CSV = True
RESULTS_CSV_FILE = Path(__file__).with_name("focal_spot_pcc_results.csv")


# =============================================================================
# DATA LOADING AND GRID HANDLING
# =============================================================================

def load_2d_array(path: Path) -> np.ndarray:
    """Load a finite two-dimensional NumPy array."""
    if not path.exists():
        raise FileNotFoundError(f"File does not exist:\n{path}")

    array = np.asarray(np.load(path), dtype=np.float64).squeeze()

    if array.ndim != 2:
        raise ValueError(
            f"Expected a 2-D array in {path.name}, but found shape {array.shape}"
        )

    if not np.isfinite(array).all():
        raise ValueError(f"{path.name} contains NaN or infinite values")

    return array


def load_extent_um(path: Path) -> tuple[float, float, float, float]:
    """Load [xmin, xmax, ymin, ymax] in micrometres."""
    if not path.exists():
        raise FileNotFoundError(f"Extent file does not exist:\n{path}")

    extent = np.asarray(np.load(path), dtype=np.float64).squeeze().ravel()

    if extent.size != 4:
        raise ValueError(
            f"Expected four extent values [xmin, xmax, ymin, ymax], "
            f"but found shape {extent.shape}"
        )

    xmin, xmax, ymin, ymax = map(float, extent)

    if not np.isfinite(extent).all():
        raise ValueError("The focal-spot extent contains NaN or infinite values")

    if xmax <= xmin or ymax <= ymin:
        raise ValueError(
            f"Invalid focal-spot extent: {[xmin, xmax, ymin, ymax]}"
        )

    return xmin, xmax, ymin, ymax


def peak_normalise(image: np.ndarray) -> np.ndarray:
    """Clip negative numerical noise and peak-normalise an intensity map."""
    image = np.clip(np.asarray(image, dtype=np.float64), 0.0, None)
    peak = float(np.max(image))

    if peak <= 0:
        raise ValueError("Cannot normalise an array whose peak is zero")

    return image / peak


def resample_to_reference_grid(
    image: np.ndarray,
    extent_um: tuple[float, float, float, float],
    reference_shape: tuple[int, int],
) -> np.ndarray:
    """Bilinearly resample an image onto the desired focal-spot grid.

    The same physical extent is assumed for all focal spots. If the array
    already has the desired shape, it is returned unchanged.
    """
    image = np.asarray(image, dtype=np.float64)

    if image.shape == reference_shape:
        return image.copy()

    xmin, xmax, ymin, ymax = extent_um

    source_y = np.linspace(ymin, ymax, image.shape[0])
    source_x = np.linspace(xmin, xmax, image.shape[1])

    target_y = np.linspace(ymin, ymax, reference_shape[0])
    target_x = np.linspace(xmin, xmax, reference_shape[1])

    # Interpolate in x for each source row.
    x_resampled = np.empty((image.shape[0], reference_shape[1]), dtype=np.float64)
    for row_index, row in enumerate(image):
        x_resampled[row_index] = np.interp(
            target_x,
            source_x,
            row,
            left=0.0,
            right=0.0,
        )

    # Interpolate in y for each target-grid column.
    output = np.empty(reference_shape, dtype=np.float64)
    for column_index in range(reference_shape[1]):
        output[:, column_index] = np.interp(
            target_y,
            source_y,
            x_resampled[:, column_index],
            left=0.0,
            right=0.0,
        )

    return output


def build_comparison_mask(
    reference: np.ndarray,
    extent_um: tuple[float, float, float, float],
    focal_half_width_um: float | None,
    reference_threshold: float | None,
) -> np.ndarray:
    """Build the physical-window and optional signal-threshold mask."""
    xmin, xmax, ymin, ymax = extent_um

    x_um = np.linspace(xmin, xmax, reference.shape[1])
    y_um = np.linspace(ymin, ymax, reference.shape[0])

    mask = np.ones(reference.shape, dtype=bool)

    if focal_half_width_um is not None:
        if focal_half_width_um <= 0:
            raise ValueError("FOCAL_HALF_WIDTH_UM must be positive or None")

        x_mask = np.abs(x_um) <= focal_half_width_um
        y_mask = np.abs(y_um) <= focal_half_width_um
        mask &= y_mask[:, None] & x_mask[None, :]

    if reference_threshold is not None:
        if not 0 <= reference_threshold < 1:
            raise ValueError("REFERENCE_THRESHOLD must lie in [0, 1)")
        mask &= reference >= reference_threshold

    if np.count_nonzero(mask) < 2:
        raise ValueError(
            "The selected comparison region contains fewer than two pixels"
        )

    return mask


# =============================================================================
# PEARSON CORRELATION
# =============================================================================

def pearson_correlation(
    test: np.ndarray,
    reference: np.ndarray,
    mask: np.ndarray,
) -> float:
    """Calculate the image PCC using the selected comparison pixels."""
    if test.shape != reference.shape:
        raise ValueError(
            f"Shape mismatch: test {test.shape}, reference {reference.shape}"
        )

    test_values = np.asarray(test[mask], dtype=np.float64)
    reference_values = np.asarray(reference[mask], dtype=np.float64)

    test_centered = test_values - np.mean(test_values)
    reference_centered = reference_values - np.mean(reference_values)

    denominator = (
        np.linalg.norm(test_centered)
        * np.linalg.norm(reference_centered)
    )

    if denominator == 0:
        raise ValueError(
            "PCC is undefined because one selected array is constant"
        )

    return float(np.dot(test_centered, reference_centered) / denominator)


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:
    desired = load_2d_array(DESIRED_FOCAL_SPOT_FILE)
    extent_um = load_extent_um(COMMON_FOCAL_SPOT_EXTENT_FILE)

    focal_spot_files = {
        "Random phase plate (RPP)": RPP_FOCAL_SPOT_FILE,
        "Continuous phase plate (CPP)": CONTINUOUS_FOCAL_SPOT_FILE,
        "Distributed phase plate (DPP)": DISTRIBUTED_FOCAL_SPOT_FILE,
    }

    focal_spots = {
        name: load_2d_array(path)
        for name, path in focal_spot_files.items()
    }

    print("\nLoaded focal-spot shapes:")
    print(f"  Desired focal spot: {desired.shape}")
    for name, image in focal_spots.items():
        print(f"  {name}: {image.shape}")

    # Put every generated focal spot on the desired focal spot's grid.
    focal_spots = {
        name: resample_to_reference_grid(
            image,
            extent_um,
            desired.shape,
        )
        for name, image in focal_spots.items()
    }

    if PEAK_NORMALISE:
        desired = peak_normalise(desired)
        focal_spots = {
            name: peak_normalise(image)
            for name, image in focal_spots.items()
        }

    mask = build_comparison_mask(
        desired,
        extent_um,
        FOCAL_HALF_WIDTH_UM,
        REFERENCE_THRESHOLD,
    )

    results = []
    for name, image in focal_spots.items():
        pcc = pearson_correlation(image, desired, mask)
        results.append((name, pcc))

    results.sort(key=lambda item: item[1], reverse=True)

    print("\nPearson correlation against the desired focal spot:")
    for name, pcc in results:
        print(f"  {name:<34s} PCC = {pcc:.6f}")

    print("\nRanking:")
    for rank, (name, pcc) in enumerate(results, start=1):
        print(f"  {rank}. {name}: {pcc:.6f}")

    print(f"\nPixels included in comparison: {np.count_nonzero(mask):,}")

    if FOCAL_HALF_WIDTH_UM is None:
        print("Comparison region: complete saved focal plane")
    else:
        print(
            "Comparison region: "
            f"x, y = +/-{FOCAL_HALF_WIDTH_UM:.3f} um"
        )

    if REFERENCE_THRESHOLD is not None:
        print(
            "Desired-intensity threshold: "
            f"{REFERENCE_THRESHOLD:.3e} of peak"
        )

    if SAVE_RESULTS_CSV:
        with RESULTS_CSV_FILE.open("w", newline="", encoding="utf-8") as file:
            writer = csv.writer(file)
            writer.writerow(["Rank", "Phase plate", "PCC"])
            for rank, (name, pcc) in enumerate(results, start=1):
                writer.writerow([rank, name, f"{pcc:.10f}"])

        print(f"\nSaved results to:\n  {RESULTS_CSV_FILE}")


if __name__ == "__main__":
    main()
